spring:
  application:
    name: order-service

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8070

grpc:
  client:
    ProductService:
      address: static://localhost:9090
      keep-alive-without-calls: true
      negotiation-type: plaintext






