spring:
  application:
    name: order-service

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8070

management:
  tracing:
    sampling:
      probability: 1.0






