spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: OrderConfirmation:org.microservices.payment.kafka.order.OrderConfirmation

server:
  port: 8060
